### ISSUE TITLE
Flags not visibile

### ISSUE THREAD

**Issue by mukeshsolanki** [heetch/Android-country-picker#5]
The flags are not visible when you make a release version of the app with proguard enabled and shrinkResources set to true

**Comment by iampawan** [comment]
Same issue.. Please help asap .
Thanks

**Comment by iampawan** [comment]
@EKami Please fix this asap

**Comment by godardt** [comment]
I don't have the time to fix this for the moment as I have more important matter to do. If you need it asap don't hesitate to open up a PR with the fixes you added guys it will be greatly appreciated.

**Comment by agonist** [comment]
Fixed in [1.0.6](https://github.com/heetch/Android-country-picker/releases/tag/1.0.6)
